/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WordpressRouteImport } from './routes/wordpress'
import { Route as ShopifyRouteImport } from './routes/shopify'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as DomainsRouteImport } from './routes/domains'
import { Route as DevsRouteImport } from './routes/devs'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as IndexRouteImport } from './routes/index'

const WordpressRoute = WordpressRouteImport.update({
  id: '/wordpress',
  path: '/wordpress',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopifyRoute = ShopifyRouteImport.update({
  id: '/shopify',
  path: '/shopify',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsRoute = DomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const DevsRoute = DevsRouteImport.update({
  id: '/devs',
  path: '/devs',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/devs': typeof DevsRoute
  '/domains': typeof DomainsRoute
  '/invoices': typeof InvoicesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/shopify': typeof ShopifyRoute
  '/wordpress': typeof WordpressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/devs': typeof DevsRoute
  '/domains': typeof DomainsRoute
  '/invoices': typeof InvoicesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/shopify': typeof ShopifyRoute
  '/wordpress': typeof WordpressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/devs': typeof DevsRoute
  '/domains': typeof DomainsRoute
  '/invoices': typeof InvoicesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/shopify': typeof ShopifyRoute
  '/wordpress': typeof WordpressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers'
    | '/devs'
    | '/domains'
    | '/invoices'
    | '/reports'
    | '/settings'
    | '/shopify'
    | '/wordpress'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customers'
    | '/devs'
    | '/domains'
    | '/invoices'
    | '/reports'
    | '/settings'
    | '/shopify'
    | '/wordpress'
  id:
    | '__root__'
    | '/'
    | '/customers'
    | '/devs'
    | '/domains'
    | '/invoices'
    | '/reports'
    | '/settings'
    | '/shopify'
    | '/wordpress'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersRoute: typeof CustomersRoute
  DevsRoute: typeof DevsRoute
  DomainsRoute: typeof DomainsRoute
  InvoicesRoute: typeof InvoicesRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  ShopifyRoute: typeof ShopifyRoute
  WordpressRoute: typeof WordpressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wordpress': {
      id: '/wordpress'
      path: '/wordpress'
      fullPath: '/wordpress'
      preLoaderRoute: typeof WordpressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopify': {
      id: '/shopify'
      path: '/shopify'
      fullPath: '/shopify'
      preLoaderRoute: typeof ShopifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains': {
      id: '/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof DomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devs': {
      id: '/devs'
      path: '/devs'
      fullPath: '/devs'
      preLoaderRoute: typeof DevsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersRoute: CustomersRoute,
  DevsRoute: DevsRoute,
  DomainsRoute: DomainsRoute,
  InvoicesRoute: InvoicesRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  ShopifyRoute: ShopifyRoute,
  WordpressRoute: WordpressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
